-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`) VALUES
('midnightblue', 'Midnight Blue', 'Blue'),
('mintcream', 'Mint Cream', 'Greyscale'),
('mistyrose', 'Misty Rose', 'Pink'),
('moccasin', 'Moccasin', 'Brown'),
('mythical', 'Mythical', 'Purple'),
('navajowhite', 'Navajo White', 'Brown'),
('navy', 'Navy', 'Blue'),
('normal', 'Normal', 'Greyscale'),
('oldlace', 'Old Lace', 'Brown'),
('olive', 'Olive', 'Green'),
('olivedrab', 'Olive Drab', 'Green'),
('Orange', 'Orange', 'Orange'),
('orangered', 'Orange Red', 'Red'),
('orchid', 'Orchid', 'Pink'),
('palegoldenrod', 'Pale Goldenrod', 'Yellow'),
('palegreen', 'Pale Green', 'Green'),
('paleturquoise', 'Pale Turquoise', 'Blue'),
('palevioletred', 'Pale Violet Red', 'Red'),
('papayawhip', 'Papaya Whip', 'Brown'),
('peachpuff', 'Peach Puff', 'Brown'),
('peru', 'Peru', 'Brown'),
('pink', 'Pink', 'Pink'),
('plum', 'Plum', 'Purple'),
('powderblue', 'Powder Blue', 'Blue'),
('purple', 'Purple', 'Purple'),
('rare', 'Rare', 'Blue'),
('red', 'Red', 'Red'),
('rosybrown', 'Rosy Brown', 'Brown'),
('royalblue', 'Royal Blue', 'Blue'),
('saddlebrown', 'Saddle Brown', 'Brown'),
('salmon', 'Salmon', 'Orange'),
('sandybrown', 'Sandy Brown', 'Brown'),
('seagreen', 'Sea Green', 'Green'),
('seashell', 'Seashell', 'Greyscale'),
('selfmade', 'Selfmade', 'Green'),
('sienna', 'Sienna', 'Brown'),
('silver', 'Silver', 'Greyscale'),
('skyblue', 'Sky Blue', 'Blue'),
('slateblue', 'Slate Blue', 'Blue'),
('slategrey', 'Slate Grey', 'Greyscale'),
('snow', 'Snow', 'Greyscale'),
('springgreen', 'Spring Green', 'Green'),
('steelblue', 'Steel Blue', 'Blue'),
('strange', 'Strange', 'Orange'),
('tan', 'Tan', 'Brown'),
('teal', 'Teal', 'Blue'),
('thistle', 'Thistle', 'Purple'),
('tomato', 'Tomato', 'Red'),
('turquoise', 'Turquoise', 'Blue'),
('uncommon', 'Uncommon', 'Greyscale'),
('unique', 'Unique', 'Yellow'),
('unusual', 'Unusual', 'Purple'),
('valve', 'Valve', 'Purple'),
('vintage', 'Vintage', 'Blue'),
('violet', 'Violet', 'Pink'),
('wheat', 'Wheat', 'Brown'),
('white', 'White', 'Greyscale'),
('whitesmoke', 'White Smoke', 'Greyscale'),
('yellow', 'Yellow', 'Yellow'),
('yellowgreen', 'Yellow Green', 'Yellow');
