-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`) VALUES
('forestgreen', 'Forest Green', 'Green'),
('frozen', 'Frozen', 'Blue'),
('fuschia', 'Fuschia', 'Pink'),
('fullblue', 'Full Blue', 'Blue'),
('fullred', 'Full Red', 'Red'),
('gainsboro', 'Gainsboro', 'Greyscale'),
('genuine', 'Genuine', 'Green'),
('ghostwhite', 'Ghost White', 'Greyscale'),
('gold', 'Gold', 'Yellow'),
('goldenrod', 'Goldenrod', 'Yellow'),
('Green', 'Green', 'Green'),
('greenyellow', 'Green Yellow', 'Green'),
('grey', 'Grey', 'Greyscale'),
('haunted', 'Haunted', 'Green'),
('honeydew', 'Honeydew', 'Green'),
('hotpink', 'Hot Pink', 'Pink'),
('immortal', 'Immortal', 'Yellow'),
('indianred', 'Indian Red', 'Red'),
('indigo', 'Indigo', 'Purple'),
('ivory', 'Ivory', 'Greyscale'),
('khaki', 'Khaki', 'Brown'),
('lavender', 'Lavender', 'Purple'),
('lavenderblush', 'Lavender Blush', 'Pink'),
('lawngreen', 'Lawn Green', 'Green'),
('legendary', 'Legendary', 'Purple'),
('lemonchiffon', 'Lemon Chiffon', 'Yellow'),
('lightblue', 'Light Blue', 'Blue'),
('lightcoral', 'Light Coral', 'Pink'),
('lightcyan', 'Light Cyan', 'Blue'),
('lightgoldenrodyellow', 'Light Goldenrod', 'Yellow'),
('lightgreen', 'Light Green', 'Green'),
('lightgrey', 'Light Grey', 'Greyscale'),
('lightpink', 'Light Pink', 'Pink'),
('lightsalmon', 'Light Salmon', 'Orange'),
('lightseagreen', 'Light Sea Green', 'Blue'),
('lightskyblue', 'Light Sky Blue', 'Blue'),
('lightslategrey', 'Light Slate Grey', 'Greyscale'),
('lightsteelblue', 'Light Steel Blue', 'Blue'),
('lightyellow', 'Light Yellow', 'Yellow'),
('lime', 'Lime', 'Green'),
('limegreen', 'Lime Green', 'Green'),
('linen', 'Linen', 'Brown'),
('magenta', 'Magenta', 'Pink'),
('maroon', 'Maroon', 'Red'),
('mediumaquamarine', 'Medium Aquamarine', 'Blue'),
('mediumblue', 'Medium Blue', 'Blue'),
('mediumorchid', 'Medium Orchid', 'Purple'),
('mediumpurple', 'Medium Purple', 'Purple'),
('mediumseagreen', 'Medium Sea Green', 'Green'),
('mediumslateblue', 'Medium Slate Blue', 'Blue'),
('mediumspringgreen', 'Medium Spring Green', 'Green'),
('mediumturquoise', 'Medium Turquoise', 'Blue'),
('mediumvioletred', 'Medium Violet Red', 'Pink');
