-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`) VALUES
('gray', 'Gray', 'Greyscale'),
('dimgray', 'Dim Gray', 'Greyscale'),
('lightgray', 'Light Gray', 'Greyscale'),
('darkslategray', 'Dark Slate Gray', 'Greyscale'),
('aliceblue', 'Alice Blue', 'Blue'),
('allies', 'Allies', 'Green'),
('ancient', 'Ancient', 'Red'),
('antiquewhite', 'Antique White', 'Greyscale'),
('aqua', 'Aqua', 'Blue'),
('aquamarine', 'Aquamarine', 'Blue'),
('arcana', 'Arcana', 'Green'),
('axis', 'Axis', 'Red'),
('azure', 'Azure', 'Blue'),
('beige', 'Beige', 'Greyscale'),
('bisque', 'Bisque', 'Brown'),
('black', 'Black', 'Greyscale'),
('blanchedalmond', 'Blanched Almond', 'Greyscale'),
('blue', 'Blue', 'Blue'),
('blueviolet', 'Blue Violet', 'Purple'),
('brown', 'Brown', 'Brown'),
('burlywood', 'Burly Wood', 'Brown'),
('cadetblue', 'Cadet Blue', 'Blue'),
('chartreuse', 'Charteuse', 'Green'),
('chocolate', 'Chocolate', 'Brown'),
('collectors', 'Collectors', 'Red'),
('common', 'Common', 'Greyscale'),
('community', 'Community', 'Green'),
('coral', 'Coral', 'Orange'),
('cornflowerblue', 'Cornflower Blue', 'Blue'),
('cornsilk', 'Corn Silk', 'Brown'),
('corrupted', 'Corrupted', 'Red'),
('crimson', 'Crimson', 'Red'),
('cyan', 'Cyan', 'Blue'),
('darkblue', 'Dark Blue', 'Blue'),
('darkcyan', 'Dark Cyan', 'Blue'),
('darkgoldenrod', 'Dark Goldenrod', 'Yellow'),
('darkgray', 'Dark Grey', 'Greyscale'),
('darkgreen', 'Dark Green', 'Green'),
('darkkhaki', 'Dark Khaki', 'Brown'),
('darkmagenta', 'Dark Magenta', 'Purple'),
('darkolivegreen', 'Dark Olive Green', 'Green'),
('darkorange', 'Dark Orange', 'Orange'),
('darkorchid', 'Dark Orchid', 'Purple'),
('darkred', 'Dark Red', 'Red'),
('darksalmon', 'Dark Salmon', 'Orange'),
('darkseagreen', 'Dark Sea Green', 'Green'),
('darkslateblue', 'Dark Slate Blue', 'Blue'),
('darkslategrey', 'Dark Slate Grey', 'Greyscale'),
('darkturquoise', 'Dark Turquoise', 'Blue'),
('darkviolet', 'Dark Violet', 'Purple'),
('deeppink', 'Deep Pink', 'Pink'),
('deepskyblue', 'Deep Sky Blue', 'Blue'),
('dimgrey', 'Dim Grey', 'Greyscale'),
('dodgerblue', 'Dodger Blue', 'Blue'),
('exalted', 'Exalted', 'Greyscale'),
('firebrick', 'Fire Brick', 'Red'),
('floralwhite', 'Floral White', 'Greyscale');
