-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`, `price`) VALUES
('rmediumstonegrey', 'R. Medium Stone Grey', 'Greyscale', 200),
('rmedredviolet', 'R. Medium Red Violet', 'Purple', 200),
('rmedyellowishgreen', 'R. Medium Yellow Green', 'Green', 200),
('rmedyellowishorange', 'R. Medium Yellow Orange', 'Orange', 200),
('rmidgrey', 'R. Mid Grey', 'Greyscale', 200),
('rmint', 'R. Mint', 'Green', 200),
('rmoss', 'R. Moss', 'Green', 200),
('rmulberry', 'R. Mulberry', 'Purple', 200),
('rnavyblue', 'R. Navy Blue', 'Blue', 200),
('rneonorange', 'R. Neon Orange', 'Orange', 200),
('rnewyeller', 'R. New Yeller', 'Yellow', 200),
('rnougat', 'R. Nougat', 'Brown', 200),
('rolive', 'R. Olive', 'Green', 200),
('rolivine', 'R. Olivine', 'Green', 200),
('royster', 'R. Oyster', 'Greyscale', 200),
('rparsleygreen', 'R. Parsley Green', 'Green', 200),
('rpastelblue', 'R. Pastel Blue', 'Blue', 200),
('rpastelbluegreen', 'R. Pastel Blue Green', 'Blue', 200),
('rpastelbrown', 'R. Pastel Brown', 'Brown', 200),
('rpastelgreen', 'R. Pastel Green', 'Green', 200),
('rpastellightblue', 'R. Pastel Light Blue', 'Blue', 200),
('rpastelorange', 'R. Pastel Orange', 'Orange', 200),
('rpastelviolet', 'R. Pastel Violet', 'Purple', 200),
('rpastelyellow', 'R. Pastel Yellow', 'Yellow', 200),
('rpearl', 'R. Pearl', 'Greyscale', 200),
('rpersimmon', 'R. Persimmon', 'Orange', 200),
('rpinecone', 'R. Pinecone', 'Brown', 200),
('rpink', 'R. Pink', 'Pink', 200),
('rplum', 'R. Plum', 'Purple', 200),
('rposphwhite', 'R. Posph. White', 'Greyscale', 200),
('rquillgrey', 'R. Quill Grey', 'Greyscale', 200),
('rreallyblack', 'R. Really Black', 'Greyscale', 200),
('rreallyblue', 'R. Really Blue', 'Blue', 200),
('rreallyred', 'R. Really Red', 'Red', 200),
('rreddishbrown', 'R. Reddish Brown', 'Brown', 200),
('rreddishlilac', 'R. Reddish Lilac', 'Purple', 200),
('rroyalblue', 'R. Royal Blue', 'Blue', 200),
('rroyalpurple', 'R. Royal Purple', 'Purple', 200),
('rrust', 'R. Rust', 'Brown', 200),
('rsagegreen', 'R. Sage Green', 'Green', 200),
('rsalmon', 'R. Salmon', 'Pink', 200),
('rsandblue', 'R. Sand Blue', 'Blue', 200),
('rsandgreen', 'R. Sand Green', 'Green', 200);
