-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`, `price`) VALUES
('ralder', 'R. Alder', 'Purple', 200),
('rartichoke', 'R. Artichoke', 'Green', 200),
('rbabyblue', 'R. Baby Blue', 'Blue', 200),
('rbeige', 'R. Beige', 'Brown', 200),
('rblack', 'R. Black', 'Greyscale', 200),
('rbrickyellow', 'R. Brick Yellow', 'Brown', 200),
('rbrightblue', 'R. Bright Blue', 'Blue', 200),
('rbrightbluishgreen', 'R. Bright Blue Green', 'Blue', 200),
('rbrightbluishviolet', 'R. Bright Blue Violet', 'Blue', 200),
('rbrightgreen', 'R. Bright Green', 'Green', 200),
('rbrightorange', 'R. Bright Orange', 'Orange', 200),
('rbrightpurple', 'R. Bright Purple', 'Pink', 200),
('rbrightred', 'R. Bright Red', 'Red', 200),
('rbrightreddishlilac', 'R. Bright Red Lilac', 'Purple', 200),
('rbrightreddishorange', 'R. Bright Red Orange', 'Orange', 200),
('rbrightreddishviolet', 'R. Bright Red Violet', 'Purple', 200),
('rbrightviolet', 'R. Bright Violet', 'Purple', 200),
('rbrightyellow', 'R. Bright Yellow', 'Yellow', 200),
('rbrightyellowishgreen', 'R. Bright Yellow Green', 'Green', 200),
('rbrightyellowishorange', 'R. Bright Yellow Orange', 'Orange', 200),
('rbronze', 'R. Bronze', 'Brown', 200),
('rbrown', 'R. Brown', 'Brown', 200),
('rburgundy', 'R. Burgundy', 'Brown', 200),
('rburlap', 'R. Burlap', 'Brown', 200),
('rburntsienna', 'R. Burnt Sienna', 'Brown', 200),
('rbuttermilk', 'R. Buttermilk', 'Yellow', 200),
('rcadetblue', 'R. Cadet Blue', 'Blue', 200),
('rcamo', 'R. Camo', 'Green', 200),
('rcarnationpink', 'R. Carnation Pink', 'Pink', 200),
('rcashmere', 'R. Cashmere', 'Brown', 200),
('rcloudygrey', 'R. Cloudy Grey', 'Greyscale', 200),
('rcocoa', 'R. Cocoa', 'Brown', 200),
('rcoolyellow', 'R. Cool Yellow', 'Yellow', 200),
('rcopper', 'R. Copper', 'Brown', 200),
('rcork', 'R. Cork', 'Brown', 200),
('rcrimson', 'R. Crimson', 'Red', 200),
('rcurry', 'R. Curry', 'Brown', 200),
('rcyan', 'R. Cyan', 'Blue', 200),
('rdaisyorange', 'R. Daisy Orange', 'Yellow', 200),
('rdarkblue', 'R. Dark Blue', 'Blue', 200),
('rdarkcurry', 'R. Dark Curry', 'Brown', 200),
('rdarkgreen', 'R. Dark Green', 'Green', 200),
('rdarkgrey', 'R. Dark Grey', 'Greyscale', 200),
('rdarkindigo', 'R. Dark Indigo', 'Purple', 200),
('rdarknougat', 'R. Dark Nougat', 'Brown', 200),
('rdarkorange', 'R. Dark Orange', 'Brown', 200),
('rdarkred', 'R. Dark Red', 'Red', 200),
('rdarkroyalblue', 'R. Dark Royal Blue', 'Blue', 200),
('rdarkstonegrey', 'R. Dark Stone Grey', 'Greyscale', 200),
('rdarktaupe', 'R. Dark Taupe', 'Brown', 200),
('rdeepblue', 'R. Deep Blue', 'Blue', 200),
('rdeeporange', 'R. Deep Orange', 'Orange', 200),
('rdirtbrown', 'R. Dirt Brown', 'Brown', 200),
('rdoveblue', 'R. Dove Blue', 'Blue', 200),
('rdustyrose', 'R. Dusty Rose', 'Red', 200),
('rearthblue', 'R. Earth Blue', 'Blue', 200),
('rearthgreen', 'R. Earth Green', 'Green', 200),
('rearthorange', 'R. Earth Orange', 'Brown', 200);
