-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`, `price`) VALUES
('rearthyellow', 'R. Earth Yellow', 'Brown', 200),
('reggplant', 'R. Eggplant', 'Purple', 200),
('relectricblue', 'R. Electric Blue', 'Blue', 200),
('rfadedgreen', 'R. Faded Green', 'Green', 200),
('rfawnbrown', 'R. Fawn Brown', 'Brown', 200),
('rfireyellow', 'R. Fire Yellow', 'Yellow', 200),
('rflamereddishorange', 'R. Flame Red Orange', 'Orange', 200),
('rflameyellowishorange', 'R. Flame Yellow Orange', 'Orange', 200),
('rflint', 'R. Flint', 'Greyscale', 200),
('rfog', 'R. Fog', 'Greyscale', 200),
('rforestgreen', 'R. Forest Green', 'Green', 200),
('rfossil', 'R. Fossil', 'Greyscale', 200),
('rghostgrey', 'R. Ghost Grey', 'Greyscale', 200),
('rgold', 'R. Gold', 'Yellow', 200),
('rgrey', 'R. Grey', 'Greyscale', 200),
('rgrime', 'R. Grime', 'Green', 200),
('rgunmetallic', 'R. Gun Metallic', 'Greyscale', 200),
('rhotpink', 'R. Hot Pink', 'Pink', 200),
('rhurricanegrey', 'R. Hurricane Grey', 'Greyscale', 200),
('rinstitutionalwhite', 'R. Institutional White', 'Greyscale', 200),
('rkhaki', 'R. Khaki', 'Brown', 200),
('rlapis', 'R. Lapis', 'Blue', 200),
('rlaurelgreen', 'R. Laurel Green', 'Green', 200),
('rlavender', 'R. Lavender', 'Purple', 200),
('rlightblue', 'R. Light Blue', 'Blue', 200),
('rlightbluishgreen', 'R. Light Blue Green', 'Blue', 200),
('rlightbluishviolet', 'R. Light Blue Violet', 'Blue', 200),
('rlightbrickyellow', 'R. Light Brick Yellow', 'Brown', 200),
('rlightgreenmint', 'R. Light Mint Green', 'Green', 200),
('rlightgrey', 'R. Light Grey', 'Greyscale', 200),
('rlightlilac', 'R. Light Lilac', 'Purple', 200),
('rlightorange', 'R. Light Orange', 'Brown', 200),
('rlightorangebrown', 'R. Light Orange Brown', 'Brown', 200),
('rlightpink', 'R. Light Pink', 'Pink', 200),
('rlightpurple', 'R. Light Purple', 'Pink', 200),
('rlightred', 'R. Light Red', 'Red', 200),
('rlightredviolet', 'R. Light Red Violet', 'Purple', 200),
('rlightroyalblue', 'R. Light Royal Blue', 'Blue', 200),
('rlightstonegrey', 'R. Light Stone Grey', 'Greyscale', 200),
('rlightyellow', 'R. Light Yellow', 'Yellow', 200),
('rlightyellowishgreen', 'R. Light Yellow Green', 'Green', 200),
('rlightyellowishorange', 'R. Light Yellow Orange', 'Brown', 200),
('rlilac', 'R. Lilac', 'Purple', 200),
('rlilywhite', 'R. Lily White', 'Greyscale', 200),
('rlimegreen', 'R. Lime Green', 'Green', 200),
('rlinen', 'R. Linen', 'Brown', 200),
('rmagenta', 'R. Magenta', 'Pink', 200),
('rmaroon', 'R. Maroon', 'Red', 200),
('rmauve', 'R. Mauve', 'Purple', 200),
('rmedbluishgreen', 'R. Medium Blue Green', 'Blue', 200),
('rmedgreen', 'R. Medium Green', 'Green', 200),
('rmediumblue', 'R. Medium Blue', 'Blue', 200),
('rmediumbluishviolet', 'R. Medium Blue Violet', 'Blue', 200),
('rmediumlilac', 'R. Medium Lilac', 'Purple', 200),
('rmediumorange', 'R. Medium Orange', 'Orange', 200),
('rmediumred', 'R. Medium Red', 'Red', 200),
('rmediumroyalblue', 'R. Medium Royal Blue', 'Blue', 200);
