-- ?17
REPLACE INTO `quasar`.`chat_colors` (`format`, `name`, `category`, `price`) VALUES
('rsandred', 'R. Sand Red', 'Red', 200),
('rsandviolet', 'R. Sand Violet', 'Purple', 200),
('rseagreen', 'R. Sea Green', 'Green', 200),
('rseashell', 'R. Sea Shell', 'Pink', 200),
('rshamrock', 'R. Shamrock', 'Green', 200),
('rsilver', 'R. Silver', 'Greyscale', 200),
('rslimegreen', 'R. Slime Green', 'Green', 200),
('rsmokygrey', 'R. Smoky Grey', 'Greyscale', 200),
('rsteelblue', 'R. Steel Blue', 'Blue', 200),
('rstormblue', 'R. Storm Blue', 'Blue', 200),
('rsunrise', 'R. Sunrise', 'Purple', 200),
('rtawny', 'R. Tawny', 'Brown', 200),
('rteal', 'R. Teal', 'Blue', 200),
('rterracotta', 'R. Terra Cotta', 'Brown', 200),
('rtoothpaste', 'R. Toothpaste', 'Blue', 200),
('rtrblue', 'R. TBlue', 'Blue', 200),
('rtrbrightbluishviolet', 'R. Tr. BBlue Violet', 'Blue', 200),
('rtrgreen', 'R. TGreen', 'Green', 200),
('rtrlgblue', 'R. Light TBlue', 'Blue', 200),
('rtrlilac', 'R. Tr. Lilac', 'Purple', 200),
('rtrmedireddishviolet', 'R. Med TRed Violet', 'Pink', 200),
('rtrred', 'R. TRed', 'Red', 200),
('rtryellow', 'R. TYellow', 'Yellow', 200),
('rturquoise', 'R. Turquoise', 'Blue', 200),
('rwarmyellowishorange', 'R. Warm Yellow Orange', 'Brown', 200),
('rwheat', 'R. Wheat', 'Brown', 200),
('rwhite', 'R. White', 'Greyscale', 200);
