-- ?12
REPLACE INTO `quasar`.`sounds` (`item_id`, `name`, `filepath`, `cooldown`, `creator_id`, `price`, `activation_phrase`) VALUES
('snd_fwrb', 'Fart (w Reverb)', 'quasar/fwr.mp3', 2, 'QUASAR', 1000, 'fart'),
('snd_gate', 'OPEN THE GATE', 'quasar/open_the_gate.mp3', 0.1, 'QUASAR', 250, 'OPEN THE GATE!'),
('snd_guts', "Gutsman's Ass", 'quasar/gutsman.mp3', 2, 'QUASAR', 500, 'gutsman'),
('snd_hkwp', 'Waterphone', 'quasar/hkwphone.mp3', 4.2, 'QUASAR', 1500, 'dramatic sting'),
('snd_hlml', 'Holay Molay', 'quasar/holay_molay.mp3', 0.8, 'QUASAR', 750, ':o'),
('snd_huh', 'Huh', 'quasar/huh.mp3', 0.5, 'QUASAR', 500, 'huh'),
('snd_klnm', 'Klonoa - Munya', 'quasar/klonoa_munya.mp3', 0.1, 'QUASAR', 750, 'MUNYA!'),
('snd_klnw', 'Klonoa - WAHOO!', 'quasar/klonoa_wahoo.mp3', 0.1, 'QUASAR', 750, 'WAHOO!'),
('snd_lean', 'I LOVE LEAN', 'quasar/lean.mp3', 0.3, 'QUASAR', 1000, 'I LOVE LEAN!'),
('snd_lgyd', 'Lego Yoda Scream', 'quasar/lego_yoda.mp3', 0.1, 'QUASAR', 500, 'lego yoda'),
('snd_mtpe', 'Metal Pipe', 'quasar/metal_pipe.mp3', 1, 'QUASAR', 2000, 'pipe'),
('snd_oof', 'Oof', 'quasar/oof.mp3', 0.2, 'QUASAR', 2000, 'oof'),
('snd_pngs', 'Pingas', 'quasar/pingas.mp3', 0.5, 'QUASAR', 500, 'pingas'),
('snd_rizz', 'Rizz', 'quasar/rizz.mp3', 1, 'QUASAR', 500, 'rizzler'),
('snd_shia', 'Shia LaBeouf DO IT!', 'quasar/shia_doit.mp3', 0.3, 'QUASAR', 500, 'DO IT!'),
('snd_skbd', 'Skibidi', 'quasar/skibidi.mp3', 4, 'QUASAR', 2500, 'Skibidi Dop Dop'),
('snd_smk', 'Smoke Weed', 'quasar/snoop_smoke.mp3', 1.8, 'QUASAR', 1000, 'Smoke Weed'),
('snd_spen', 'SPEEN', 'quasar/speen.mp3', 1, 'QUASAR', 750, 'SPEEN!'),
('snd_sque', 'Squee', 'quasar/squee.mp3', 0.2, 'QUASAR', 750, 'squee'),
('snd_sus', 'Among Us Sting', 'quasar/uhoh_sussy.mp3', 3, 'QUASAR', 2500, 'sus'),
('snd_tada', 'Tada', 'quasar/tada.mp3', 1, 'QUASAR', 250, 'Tada!'),
('snd_uuua', 'UUUA', 'quasar/uuua.mp3', 1, 'QUASAR', 1000, 'UUUA'),
('snd_vsce', 'VSauce Scream', 'quasar/vsauce_scream.mp3', 1, 'QUASAR', 1500, 'AA-'),
('snd_w95s', 'Windows 95 Startup', 'quasar/win95_start.mp3', 5.2, 'QUASAR', 1000, '95 Start'),
('snd_w98l', 'Windows 98 Shutdown', 'quasar/win98_shut.mp3', 3.2, 'QUASAR', 1000, '98 Shutdown'),
('snd_w98s', 'Windows 98 Startup', 'quasar/win98_start.mp3', 6.5, 'QUASAR', 1000, '98 Start'),
('snd_womy', 'Woomy', 'quasar/woomy.mp3', 0.4, 'QUASAR', 750, 'woomy'),
('snd_wooo', 'Cr1tikal Woo', 'quasar/cr1tikal_woo.mp3', 1, 'QUASAR', 1500, 'WOOOO'),
('snd_wrng', 'Wrong', 'quasar/wrong.mp3', 1, 'QUASAR', 500, 'wrong'),
('snd_wXPl', 'Windows XP Shutdown', 'quasar/winXP_shut.mp3', 2.2, 'QUASAR', 1000, 'XP Shutdown'),
('snd_wXPs', 'Windows XP Startup', 'quasar/winXP_start.mp3', 3.3, 'QUASAR', 1000, 'XP Start'),
('snd_yipe', 'Yipeee', 'quasar/yipee.mp3', 0.2, 'QUASAR', 2500, 'YIPEE!'),
('snd_yoyi', 'YOYOI', 'quasar/yoyoi.mp3', 0.5, 'QUASAR', 500, 'YOYOI!');
