-- ?14
REPLACE INTO `quasar`.`tags` (`item_id`, `name`, `display`, `creator_id`, `price`) VALUES
('tag_greg', 'Greg', 'Greg', 'QUASAR', 750),
('tag_hart', 'Heart', '<3', 'QUASAR', 2000),
('tag_hipp', 'Hippie', 'Hippie', 'QUASAR', 1000),
('tag_hist', 'Historic', 'Historic', 'Early Supporter', 0),
('tag_hlpr', 'Helper', 'Helper', 'Contributor', 0),
('tag_hmie', 'Homie', 'Homie', 'QUASAR', 1000),
('tag_hntr', 'Hunter', 'Hunter', 'QUASAR', 750),
('tag_homo', 'Homo', 'Homo', 'QUASAR', 750),
('tag_kbld', 'Kobold', 'Kobold', 'QUASAR', 500),
('tag_kilr', 'Killer', 'Killer', 'QUASAR', 500),
('tag_lady', 'Lady', 'Lady', 'QUASAR', 2500),
('tag_les', 'Lesbian', 'Lesbian', 'QUASAR', 750),
('tag_lord', 'Lord', 'Lord', 'QUASAR', 2500),
('tag_mapr', 'Mapper', 'Mapper', 'Contributor', 0),
('tag_mech', 'Mechanic', 'Mechanic', 'QUASAR', 750),
('tag_nerd', 'Nerd', 'Nerd', 'QUASAR', 500),
('tag_nonb', 'Nonbinary', 'Nonbinary', 'QUASAR', 750),
('tag_owo', 'OwO', 'OwO', 'QUASAR', 1500),
('tag_pan', 'Pansexual', 'Pan', 'QUASAR', 750),
('tag_pirt', 'Pirate', 'Pirate', 'REGULAR', 0),
('tag_poli', 'Politician', 'Politician', 'QUASAR', 7500),
('tag_rich', 'Rich', 'Rich', 'Donator', 0),
('tag_robt', 'Robot', 'Robot', 'QUASAR', 750),
('tag_sexy', 'Sexy', 'Sexy', 'QUASAR', 5000),
('tag_shek', 'Shrek', 'Shrek', 'QUASAR', 1500),
('tag_simp', 'Simp', 'Simp', 'QUASAR', 3000),
('tag_stnk', 'Stinky', 'Stinky', 'QUASAR', 1500),
('tag_stnr', 'Stoner', 'Stoner', 'QUASAR', 2500),
('tag_stpd', 'Stupid', 'Stupid', 'QUASAR', 500),
('tag_sus', 'Sus', 'Sus', 'QUASAR', 5000),
('tag_susy', 'Sussy', 'Sussy', 'QUASAR', 5000),
('tag_trns', 'Transexual', 'Trans', 'QUASAR', 750),
('tag_trsf', 'Trans F', 'TransF', 'QUASAR', 750),
('tag_trsm', 'Trans M', 'TransM', 'QUASAR', 750),
('tag_tryh', 'Tryhard', 'Tryhard', 'QUASAR', 750),
('tag_tsun', 'Tsundere', 'Tsundere', 'QUASAR', 1000),
('tag_uwu', 'UwU', 'UwU', 'QUASAR', 1500),
('tag_vip', 'VIP', 'VIP', 'Donator', 0),
('tag_vrgn', 'Virgin', 'Virgin', 'QUASAR', 1000),
('tag_weeb', 'Weeb', 'Weeb', 'QUASAR', 5000),
('tag_worm', 'Worm', 'Worm', 'QUASAR', 750),
('tag_wrdo', 'Weirdo', 'Weirdo', 'QUASAR', 1000);
