-- ?14
REPLACE INTO `quasar`.`tags` (`item_id`, `name`, `display`, `creator_id`, `price`) VALUES
('tag_ace', 'Asexual', 'Ace', 'QUASAR', 750),
('tag_alco', 'Alcoholic', 'Alcoholic', 'QUASAR', 2500),
('tag_alin', 'Alien', 'Alien', 'QUASAR', 750),
('tag_angl', 'Angel', 'Angel', 'QUASAR', 1000),
('tag_aro', 'Aromantic', 'Aro', 'QUASAR', 750),
('tag_asin', 'Assassin', 'Assassin', 'QUASAR', 1000),
('tag_baka', 'Baka', 'Baka', 'QUASAR', 750),
('tag_bi', 'Bisexual', 'Bi', 'QUASAR', 750),
('tag_bigl', 'Big Lady', 'Big Lady', 'QUASAR', 250),
('tag_bigm', 'Big Man', 'Big Man', 'QUASAR', 250),
('tag_bmer', 'Boomer', 'Boomer', 'QUASAR', 750),
('tag_bug', 'Bug', 'Bug', 'QUASAR', 250),
('tag_chad', 'Chad', 'Chad', 'QUASAR', 1000),
('tag_chkn', 'Chicken', 'Chicken', 'QUASAR', 750),
('tag_chnk', 'Chonker', 'Chonker', 'QUASAR', 750),
('tag_cont', 'Contributor', 'Contributor', 'Contributor', 0),
('tag_dank', 'Dank', 'Dank', 'QUASAR', 250),
('tag_degn', 'Degenerate', 'Degenerate', 'QUASAR', 2500),
('tag_desg', 'Designer', 'Designer', 'Contributor', 0),
('tag_dj', 'DJ', 'DJ', 'QUASAR', 750),
('tag_dmon', 'Demon', 'Demon', 'QUASAR', 1000),
('tag_dnte', 'Donator', 'Donator', 'Donator', 0),
('tag_drug', 'Druggie', 'Druggie', 'QUASAR', 2500),
('tag_dvil', 'Devil', 'Devil', 'QUASAR', 1000),
('tag_erly', 'Early Supporter', 'Early Supporter', 'Early Supporter', 0),
('tag_exlr', 'Explorer', 'Explorer', 'QUASAR', 250),
('tag_femb', 'Femboy', 'Femboy', 'QUASAR', 2500),
('tag_frek', 'Freak', 'Freak', 'QUASAR', 1000),
('tag_frnd', 'Friendly', 'Friendly', 'QUASAR', 750),
('tag_frst', 'First Day', 'First Day', 'Early Supporter', 0),
('tag_fury', 'Furry', 'Furry', 'QUASAR', 5000),
('tag_game', 'Gamer', 'Gamer', 'QUASAR', 2500),
('tag_gay', 'Gay', 'Gay', 'QUASAR', 750),
('tag_gbln', 'Goblin', 'Goblin', 'QUASAR', 500),
('tag_gdss', 'Goddess', 'Goddess', 'QUASAR', 5000),
('tag_gnme', 'Gnome', 'Gnome', 'QUASAR', 250),
('tag_god', 'God', 'God', 'QUASAR', 5000),
('tag_goon', 'Gooner', 'Gooner', 'QUASAR', 10000);
