-- ?19
CREATE TABLE IF NOT EXISTS `quasar`.`PLREPLACE_stats` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `steam64_id` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    `first_login` INT NOT NULL DEFAULT -1,
    `last_login` INT NOT NULL DEFAULT -1,
    `playtime` INT NOT NULL DEFAULT 0,
    `time_afk` INT NOT NULL DEFAULT 0,
    `points` DECIMAL NOT NULL DEFAULT 0.0,
    `kills` INT UNSIGNED NOT NULL DEFAULT 0,
    `afk_points` DECIMAL NOT NULL DEFAULT 0.0,
    `afk_kills` INT UNSIGNED NOT NULL DEFAULT 0,
    `assists` INT UNSIGNED NOT NULL DEFAULT 0,
    `afk_assists` INT UNSIGNED NOT NULL DEFAULT 0,
    `teamkills` INT UNSIGNED NOT NULL DEFAULT 0,
    `suicides` INT UNSIGNED NOT NULL DEFAULT 0,
    `most_damage_done` INT UNSIGNED NOT NULL DEFAULT 0,
    `most_damage_taken` INT UNSIGNED NOT NULL DEFAULT 0,
    `most_healing_done` INT UNSIGNED NOT NULL DEFAULT 0,
    `most_points_earned` DECIMAL NOT NULL DEFAULT 0.0,
    `most_afk_points_earned` DECIMAL NOT NULL DEFAULT 0.0,
    `highest_killstreak` INT UNSIGNED NOT NULL DEFAULT 0,
    `highest_afk_kill_streak` INT UNSIGNED NOT NULL DEFAULT 0,
    `afk_teamkills` INT UNSIGNED NOT NULL DEFAULT 0,
    `deaths` INT UNSIGNED NOT NULL DEFAULT 0,
    `afk_deaths` INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_PLREPLACE_stats_id` (`id` ASC),
    UNIQUE INDEX `idx_PLREPLACE_stats_steam64_id` (`steam64_id` ASC),
    INDEX `idx_PLREPLACE_stats_first_login` (`first_login` ASC),
    INDEX `idx_PLREPLACE_stats_last_login` (`last_login` ASC),
    INDEX `idx_PLREPLACE_stats_playtime` (`playtime` ASC),
    INDEX `idx_PLREPLACE_stats_time_afk` (`time_afk` ASC),
    INDEX `idx_PLREPLACE_stats_points` (`points` ASC),
    INDEX `idx_PLREPLACE_stats_kills` (`kills` ASC),
    INDEX `idx_PLREPLACE_stats_afk_points` (`afk_points` ASC),
    INDEX `idx_PLREPLACE_stats_afk_kills` (`afk_kills` ASC),
    INDEX `idx_PLREPLACE_stats_assists` (`assists` ASC),
    INDEX `idx_PLREPLACE_stats_afk_assists` (`afk_assists` ASC),
    INDEX `idx_PLREPLACE_stats_teamkills` (`teamkills` ASC),
    INDEX `idx_PLREPLACE_stats_suicides` (`suicides` ASC),
    INDEX `idx_PLREPLACE_stats_most_damage_done` (`most_damage_done` ASC),
    INDEX `idx_PLREPLACE_stats_most_damage_taken` (`most_damage_taken` ASC),
    INDEX `idx_PLREPLACE_stats_most_healing_done` (`most_healing_done` ASC),
    INDEX `idx_PLREPLACE_stats_most_points_earned` (`most_points_earned` ASC),
    INDEX `idx_PLREPLACE_stats_most_afk_points_earned` (`most_afk_points_earned` ASC),
    INDEX `idx_PLREPLACE_stats_highest_killstreak` (`highest_killstreak` ASC),
    INDEX `idx_PLREPLACE_stats_highest_afk_kill_streak` (`highest_afk_kill_streak` ASC),
    INDEX `idx_PLREPLACE_stats_afk_teamkills` (`afk_teamkills` ASC),
    INDEX `idx_PLREPLACE_stats_deaths` (`deaths` ASC),
    INDEX `idx_PLREPLACE_stats_afk_deaths` (`afk_deaths` ASC),
    CONSTRAINT `FK_players_PLREPLACE_stats`
    FOREIGN KEY (`steam64_id`)
    REFERENCES `quasar`.`players` (`steam64_id`)
);
