-- ?33
CREATE OR REPLACE VIEW `quasar`.`inventories` AS
SELECT
    PLYRITMS.STEAM64_ID,
    PLYRITMS.ITEM_ID,
    STRTRLS.NAME AS TRAIL_NAME,
    STRTRLS.VTF_FILEPATH,
    STRTRLS.VMT_FILEPATH,
    STRTRLS.PRICE AS TRAIL_PRICE,
    STRTAGS.NAME AS TAG_NAME,
    STRTAGS.DISPLAY,
    STRTAGS.PRICE AS TAG_PRICE,
    STRSNDS.NAME AS SOUND_NAME,
    STRSNDS.PRICE AS SOUND_PRICE,
    STRSNDS.FILEPATH,
    STRSNDS.COOLDOWN,
    STRSNDS.ACTIVATION_PHRASE,
    STRUPGD.NAME AS UPGRADE_NAME,
    STRUPGD.PRICE AS UPGRADE_PRICE,
    STRUPGD.DESCRIPTION AS UPGRADE_DESCRIPTION
FROM `quasar`.`players_items` AS PLYRITMS
LEFT JOIN `quasar`.`trails` AS STRTRLS
    ON PLYRITMS.ITEM_ID = STRTRLS.ITEM_ID
LEFT JOIN `quasar`.`tags` AS STRTAGS
    ON PLYRITMS.ITEM_ID = STRTAGS.ITEM_ID
LEFT JOIN `quasar`.`sounds` AS STRSNDS
    ON PLYRITMS.ITEM_ID = STRSNDS.ITEM_ID
LEFT JOIN `quasar`.`upgrades` AS STRUPGD
    ON PLYRITMS.ITEM_ID = STRUPGD.ITEM_ID;
