-- MySQL Script generated by MySQL Workbench
-- Sat Aug  2 18:05:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quasar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quasar` ;

-- -----------------------------------------------------
-- Schema quasar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quasar` DEFAULT CHARACTER SET utf8 ;
USE `quasar` ;

-- -----------------------------------------------------
-- Table `quasar`.`str_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_groups` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_playersgroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_playersgroups` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_playersgroups` (
  `steam_id` VARCHAR(64) NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`steam_id`, `group_id`),
  INDEX `FK_playersgroups_groups_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `FK_playersgroups_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `quasar`.`str_groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_chatcolors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_chatcolors` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_chatcolors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color_trie` VARCHAR(64) NOT NULL DEFAULT '{default}',
  `color_name` VARCHAR(64) NOT NULL DEFAULT 'Default',
  `color_type` VARCHAR(16) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`id`, `color_trie`),
  UNIQUE INDEX `color_trie_UNIQUE` (`color_trie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_chatpacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_chatpacks` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_chatpacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pack_name` VARCHAR(64) NULL DEFAULT 'SourceMod',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_colorspacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_colorspacks` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_colorspacks` (
  `color_trie` VARCHAR(64) NOT NULL,
  `pack_id` INT NOT NULL,
  PRIMARY KEY (`color_trie`, `pack_id`),
  INDEX `FK_colorspacks_chatpacks_idx` (`pack_id` ASC) VISIBLE,
  UNIQUE INDEX `color_trie_UNIQUE` (`color_trie` ASC) VISIBLE,
  CONSTRAINT `FK_colorspacks_chatpacks`
    FOREIGN KEY (`pack_id`)
    REFERENCES `quasar`.`str_chatpacks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_sounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_sounds` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_sounds` (
  `item_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `filepath` VARCHAR(256) NOT NULL,
  `cooldown` DECIMAL NULL DEFAULT 0.2,
  `price` INT NULL DEFAULT 0,
  `owner_id` VARCHAR(64) NOT NULL DEFAULT 'STORE',
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_trails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_trails` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_trails` (
  `item_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `vtf` VARCHAR(256) NOT NULL,
  `vmt` VARCHAR(256) NOT NULL,
  `price` INT NULL DEFAULT 0,
  `owner_id` VARCHAR(64) NULL DEFAULT 'STORE',
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_tags` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_tags` (
  `item_id` VARCHAR(64) NOT NULL DEFAULT 'tag_missing',
  `name` VARCHAR(64) NULL DEFAULT 'MISSINGTAG',
  `color_trie` VARCHAR(64) NULL DEFAULT 'pink',
  `price` INT NULL DEFAULT 0,
  `owner_id` VARCHAR(64) NULL DEFAULT 'STORE',
  `display` VARCHAR(64) NULL DEFAULT 'MISSINGTAG',
  PRIMARY KEY (`item_id`),
  INDEX `FK_tags_chatcolors_idx` (`color_trie` ASC) VISIBLE,
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  CONSTRAINT `FK_tags_chatcolors`
    FOREIGN KEY (`color_trie`)
    REFERENCES `quasar`.`str_chatcolors` (`color_trie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_playersitems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_playersitems` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_playersitems` (
  `steam_id` VARCHAR(64) NOT NULL,
  `item_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`steam_id`, `item_id`),
  CONSTRAINT `FK_playersitems_playersgroups`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`str_playersgroups` (`steam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_playersbank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_playersbank` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_playersbank` (
  `steam_id` VARCHAR(64) NOT NULL,
  `credits` INT NOT NULL DEFAULT 500,
  PRIMARY KEY (`steam_id`),
  CONSTRAINT `FK_playersbank_playersitems`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`str_playersitems` (`steam_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_upgrades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_upgrades` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_upgrades` (
  `item_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT 'NONE',
  `description` VARCHAR(256) NULL DEFAULT 'NONE',
  `price` INT NULL DEFAULT 0,
  `owner_id` VARCHAR(64) NULL DEFAULT 'NONE',
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `quasar`.`str_qsrloadouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_qsrloadouts` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_qsrloadouts` (
  `steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `loadout_id` INT NOT NULL DEFAULT 1,
  `trl_id` VARCHAR(64) NULL DEFAULT 'trl_none',
  `trl_color_r` INT NOT NULL DEFAULT 255,
  `trl_color_g` INT NOT NULL DEFAULT 255,
  `trl_color_b` INT NOT NULL DEFAULT 255,
  `trl_color_a` INT NOT NULL DEFAULT 255,
  `trl_width` INT NOT NULL DEFAULT 8,
  `tag_id` VARCHAR(64) NULL DEFAULT 'tag_none',
  `name_color_trie` VARCHAR(64) NOT NULL DEFAULT 'default',
  `chat_color_trie` VARCHAR(64) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`steam_id`, `loadout_id`),
  INDEX `FK_sntloadouts_playersitems_idx` (`steam_id` ASC) VISIBLE,
  INDEX `FK_sntloadouts_trails_idx` (`trl_id` ASC) VISIBLE,
  INDEX `FK_qsrloadouts_tags_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `FK_qsrloadouts_playersitems`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`str_playersitems` (`steam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_qsrloadouts_trails`
    FOREIGN KEY (`trl_id`)
    REFERENCES `quasar`.`str_trails` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_qsrloadouts_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `quasar`.`str_tags` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_classes` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_particles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_particles` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_particles` (
  `id` INT NOT NULL DEFAULT -1,
  `name` VARCHAR(256) NULL DEFAULT 'UNDEFINED',
  `type` VARCHAR(16) NULL DEFAULT 'WEAPON',
  `system_name` VARCHAR(128) NULL DEFAULT 'NONE',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_paintkits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_paintkits` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_paintkits` (
  `id` INT NOT NULL DEFAULT -1,
  `name` VARCHAR(128) NULL DEFAULT 'UNDEFINED',
  `red_color` INT NULL DEFAULT 0,
  `blu_color` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_items` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_items` (
  `id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `classname` VARCHAR(128) NULL,
  `min_level` INT NULL,
  `max_level` INT NULL,
  `slot` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_qualities` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_qualities` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_warpaints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_warpaints` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_warpaints` (
  `id` INT NOT NULL,
  `name` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_tfloadouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_tfloadouts` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_tfloadouts` (
  `steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `loadout_id` INT NOT NULL DEFAULT 1,
  `class` INT NOT NULL DEFAULT 1,
  `item_id` INT NULL DEFAULT -1,
  `quality` INT NULL DEFAULT 0,
  `level` INT NULL DEFAULT 1,
  `unusual_id` INT NULL DEFAULT 0,
  `paintkit_id` INT NULL DEFAULT 0,
  `warpaint_id` INT NULL DEFAULT 0,
  PRIMARY KEY (`steam_id`, `loadout_id`, `class`),
  INDEX `PK_tfloadouts_classes_idx` (`class` ASC) VISIBLE,
  INDEX `PK_tfloadouts_unusuals_idx` (`unusual_id` ASC) VISIBLE,
  INDEX `PK_tfloadouts_paintkits_idx` (`paintkit_id` ASC) VISIBLE,
  INDEX `PK_tfloadouts_items_idx` (`item_id` ASC) VISIBLE,
  INDEX `PK_tfloadouts_qualities_idx` (`quality` ASC) VISIBLE,
  INDEX `PK_tfloadouts_warpaints_idx` (`warpaint_id` ASC) VISIBLE,
  CONSTRAINT `PK_tfloadouts_playersitems`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`str_playersitems` (`steam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_classes`
    FOREIGN KEY (`class`)
    REFERENCES `quasar`.`tf_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_partlces`
    FOREIGN KEY (`unusual_id`)
    REFERENCES `quasar`.`tf_particles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_paintkits`
    FOREIGN KEY (`paintkit_id`)
    REFERENCES `quasar`.`tf_paintkits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `quasar`.`tf_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_qualities`
    FOREIGN KEY (`quality`)
    REFERENCES `quasar`.`tf_qualities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_tfloadouts_warpaints`
    FOREIGN KEY (`warpaint_id`)
    REFERENCES `quasar`.`tf_warpaints` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_itemsclasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_itemsclasses` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_itemsclasses` (
  `item_id` INT NOT NULL,
  `class` INT NOT NULL,
  PRIMARY KEY (`item_id`, `class`),
  INDEX `FK_itemsclasses_classes_idx` (`class` ASC) VISIBLE,
  CONSTRAINT `FK_itemsclasses_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `quasar`.`tf_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_itemsclasses_classes`
    FOREIGN KEY (`class`)
    REFERENCES `quasar`.`tf_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_attributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_attributes` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_attributes` (
  `id` INT NOT NULL,
  `name` VARCHAR(128) NULL,
  `classname` VARCHAR(128) NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `classname_UNIQUE` (`classname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`tf_itemsattributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`tf_itemsattributes` ;

CREATE TABLE IF NOT EXISTS `quasar`.`tf_itemsattributes` (
  `item_id` INT NOT NULL,
  `attribute_classname` VARCHAR(128) NOT NULL,
  `attribute_value` DECIMAL(10) NULL,
  PRIMARY KEY (`item_id`, `attribute_classname`),
  INDEX `FK_itemsattributes_attributes_idx` (`attribute_classname` ASC) VISIBLE,
  CONSTRAINT `FK_itemsattributes_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `quasar`.`tf_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_itemsattributes_attributes`
    FOREIGN KEY (`attribute_classname`)
    REFERENCES `quasar`.`tf_attributes` (`classname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_soundslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_soundslots` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_soundslots` (
  `steam_id` VARCHAR(64) NOT NULL,
  `loadout_id` INT NOT NULL DEFAULT 1,
  `slot` INT NOT NULL DEFAULT 0,
  `item_id` VARCHAR(64) NULL DEFAULT 'snd_none',
  PRIMARY KEY (`steam_id`, `loadout_id`, `slot`),
  INDEX `str_soundslots_sounds_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `str_soundslots_qsrloadouts`
    FOREIGN KEY (`steam_id` , `loadout_id`)
    REFERENCES `quasar`.`str_qsrloadouts` (`steam_id` , `loadout_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `str_soundslots_sounds`
    FOREIGN KEY (`item_id`)
    REFERENCES `quasar`.`str_sounds` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`str_tftaunts_loadouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`str_tftaunts_loadouts` ;

CREATE TABLE IF NOT EXISTS `quasar`.`str_tftaunts_loadouts` (
  `steam_id` VARCHAR(64) NOT NULL,
  `loadout_id` INT NOT NULL,
  `class` INT NOT NULL,
  `item_id` INT NULL,
  `slot` INT NOT NULL,
  `unusual_id` INT NULL,
  PRIMARY KEY (`steam_id`, `loadout_id`, `class`, `slot`),
  CONSTRAINT `FK_tauntloadouts_tfloadouts`
    FOREIGN KEY (`steam_id` , `loadout_id` , `class`)
    REFERENCES `quasar`.`str_tfloadouts` (`steam_id` , `loadout_id` , `class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `quasar` ;

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Sounds]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Sounds]` (`steam_id` INT, `item_id` INT, `name` INT, `filepath` INT, `cooldown` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Upgrades]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Upgrades]` (`steam_id` INT, `item_id` INT, `name` INT, `description` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Tags]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Tags]` (`steam_id` INT, `item_id` INT, `name` INT, `display` INT, `color_trie` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Trails]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Trails]` (`steam_id` INT, `item_id` INT, `name` INT, `vtf` INT, `vmt` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Inventory]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Inventory]` (`steam_id` INT, `item_id` INT, `upgrade_name` INT, `trail_name` INT, `sound_name` INT, `tag_name` INT, `upgrade_price` INT, `trail_price` INT, `sound_price` INT, `tag_price` INT, `upgrade_description` INT, `trail_vtf` INT, `trail_vmt` INT, `sound_filepath` INT, `sound_cooldown` INT, `tag_color` INT, `tag_display` INT);

-- -----------------------------------------------------
-- View `quasar`.`[Player Sounds]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Sounds]`;
DROP VIEW IF EXISTS `quasar`.`[Player Sounds]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Sounds]` AS
SELECT steam_id, pi.item_id, name, filepath, cooldown, price
FROM str_playersitems pi
	JOIN str_sounds snd
	ON pi.item_id = snd.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Upgrades]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Upgrades]`;
DROP VIEW IF EXISTS `quasar`.`[Player Upgrades]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Upgrades]` AS
SELECT steam_id, pi.item_id, name, description, price
FROM str_playersitems pi
	JOIN str_upgrades ugd
	ON pi.item_id = ugd.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Tags]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Tags]`;
DROP VIEW IF EXISTS `quasar`.`[Player Tags]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Tags]` AS
SELECT steam_id, pi.item_id, name, display, color_trie, price
FROM str_playersitems pi
	JOIN str_tags tag
	ON pi.item_id = tag.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Trails]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Trails]`;
DROP VIEW IF EXISTS `quasar`.`[Player Trails]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Trails]` AS
SELECT steam_id, pi.item_id, name, vtf, vmt, price
FROM str_playersitems pi
	JOIN str_trails trl
	ON pi.item_id = trl.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Inventory]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Inventory]`;
DROP VIEW IF EXISTS `quasar`.`[Player Inventory]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Inventory]` AS
SELECT  steam_id, pi.item_id, 
		upg.name upgrade_name, trl.name trail_name, snd.name sound_name, tag.name tag_name,
		upg.price upgrade_price, trl.price trail_price, snd.price sound_price, tag.price tag_price,
		upg.description upgrade_description,
		trl.vtf trail_vtf, trl.vmt trail_vmt,
		snd.filepath sound_filepath, snd.cooldown sound_cooldown,
		tag.color_trie tag_color, tag.display tag_display
FROM str_playersitems pi
	LEFT JOIN str_upgrades upg
		ON pi.item_id = upg.item_id
	LEFT JOIN str_trails trl
		ON pi.item_id = trl.item_id
	LEFT JOIN str_sounds snd
		ON pi.item_id = snd.item_id
	LEFT JOIN str_tags tag
		ON pi.item_id = tag.item_id
GROUP BY pi.item_id, steam_id, 
		upg.name, trl.name, snd.name, tag.name,
		upg.price, trl.price, snd.price, tag.price,
		upg.description,
		trl.vtf, trl.vmt,
		snd.filepath, snd.cooldown,
		tag.color_trie, tag.display;
USE `quasar`;

DELIMITER $$

USE `quasar`$$
DROP TRIGGER IF EXISTS `quasar`.`str_playersgroups_AFTER_INSERT` $$
USE `quasar`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quasar`.`str_playersgroups_AFTER_INSERT` AFTER INSERT ON `str_playersgroups` FOR EACH ROW
BEGIN
	IF (NEW.group_id = 1) THEN
		INSERT INTO str_playersitems(steam_id, item_id) VALUES (NEW.steam_id, "tag_news"), (NEW.steam_id, "tag_bgns"), (NEW.steam_id, "tag_ints"), (NEW.steam_id, "tag_exps"), (NEW.steam_id, "tag_msts"), (NEW.steam_id, "tag_pirt"), (NEW.steam_id, "ugd_clr_srcm"), (NEW.steam_id, "snd_yarr"), (NEW.steam_id, "trl_pflg") ON DUPLICATE KEY UPDATE steam_id = NEW.steam_id;
	ELSEIF (NEW.group_id = 2) THEN
		INSERT INTO str_playersitems(steam_id, item_id) VALUES (NEW.steam_id, "tag_erly"), (NEW.steam_id, "tag_hist"), (NEW.steam_id, "tag_frst"), (NEW.steam_id, "srv_rank") ON DUPLICATE KEY UPDATE steam_id = NEW.steam_id;
	ELSEIF (NEW.group_id = 3) THEN
		INSERT INTO str_playersitems(steam_id, item_id) VALUES (NEW.steam_id, "tag_cont"), (NEW.steam_id, "tag_desg"), (NEW.steam_id, "tag_mapr"), (NEW.steam_id, "srv_hlpr") ON DUPLICATE KEY UPDATE steam_id = NEW.steam_id;
	ELSEIF (NEW.group_id = 4) THEN
		INSERT INTO str_playersitems(steam_id, item_id) VALUES (NEW.steam_id, "tag_vip"), (NEW.steam_id, "tag_dnte"), (NEW.steam_id, "tag_rich"), (NEW.steam_id, "srv_rank"), (NEW.steam_id, "srv_cnme"), (NEW.steam_id, "srv_ccht") ON DUPLICATE KEY UPDATE steam_id = NEW.steam_id;
	END IF;
END$$


USE `quasar`$$
DROP TRIGGER IF EXISTS `quasar`.`str_playersitems_AFTER_INSERT` $$
USE `quasar`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quasar`.`str_playersitems_AFTER_INSERT` AFTER INSERT ON `str_playersitems` FOR EACH ROW
BEGIN
	IF NOT EXISTS (	SELECT *
					FROM str_qsrloadouts qsr
					WHERE steam_id = NEW.steam_id ) 
	AND NOT EXISTS 
				  ( SELECT *
                    FROM str_tfloadouts tf
                    WHERE steam_id = NEW.steam_id) THEN
	BEGIN
		DECLARE l_id INT DEFAULT 1;
		DECLARE c_id INT DEFAULT 1;
		generate_blank_inventory: LOOP
			IF (l_id < 4) THEN
				INSERT INTO str_qsrloadouts (steam_id, loadout_id) VALUES (NEW.steam_id, l_id) ON DUPLICATE KEY UPDATE steam_id = steam_id, loadout_id = loadout_id;
				generate_class_inventory: LOOP
					IF (c_id < 9) THEN
						INSERT INTO str_tfloadouts (steam_id, loadout_id, class) VALUES (NEW.steam_id, l_id, c_id) ON DUPLICATE KEY UPDATE steam_id = steam_id, loadout_id = loadout_id, class = class;
						SET c_id = c_id + 1;
						ITERATE generate_class_inventory;
					END IF;
					LEAVE generate_class_inventory;
					END LOOP;
				SET l_id = l_id + 1;
				SET c_id = 1;
				ITERATE generate_blank_inventory;
			END IF;
			LEAVE generate_blank_inventory;
			END LOOP;
		END;
	END IF;
END;$$


USE `quasar`$$
DROP TRIGGER IF EXISTS `quasar`.`str_qsrloadouts_BEFORE_INSERT` $$
USE `quasar`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quasar`.`str_qsrloadouts_BEFORE_INSERT` BEFORE INSERT ON `str_qsrloadouts` FOR EACH ROW
BEGIN
	IF (NEW.loadout_id > 4) THEN
		SET NEW.loadout_id = 4;
	ELSEIF (NEW.loadout_id < 1) THEN
		SET NEW.loadout_id = 1;
	END IF;
    
	IF (NEW.trl_color_r > 255) THEN
		SET NEW.trl_color_r = 255;
	ELSEIF (NEW.trl_color_r < 0) THEN
		SET NEW.trl_color_r = 0;
    END IF;

	IF (NEW.trl_color_g > 255) THEN
		SET NEW.trl_color_g = 255;
	ELSEIF (NEW.trl_color_g < 0) THEN
		SET NEW.trl_color_g = 0;
    END IF;

	IF (NEW.trl_color_b > 255) THEN
		SET NEW.trl_color_b = 255;
	ELSEIF (NEW.trl_color_b < 0) THEN
		SET NEW.trl_color_b = 0;
    END IF;

	IF (NEW.trl_color_a > 255) THEN
		SET NEW.trl_color_a = 255;
	ELSEIF (NEW.trl_color_a < 0) THEN
		SET NEW.trl_color_a = 0;
    END IF;
END;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `quasar`.`str_groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_groups` (`id`, `name`) VALUES (DEFAULT, 'REGULAR');
INSERT INTO `quasar`.`str_groups` (`id`, `name`) VALUES (DEFAULT, 'SUPPORTER');
INSERT INTO `quasar`.`str_groups` (`id`, `name`) VALUES (DEFAULT, 'CONTRIBUTOR');
INSERT INTO `quasar`.`str_groups` (`id`, `name`) VALUES (DEFAULT, 'DONATOR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_chatcolors`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_chatcolors` (`id`, `color_trie`, `color_name`, `color_type`) VALUES (0, 'default', 'Default', '\'DEFAULT\'');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_chatpacks`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_chatpacks` (`id`, `pack_name`) VALUES (DEFAULT, 'SourceMod');
INSERT INTO `quasar`.`str_chatpacks` (`id`, `pack_name`) VALUES (DEFAULT, 'Roblox');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_sounds`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_sounds` (`item_id`, `name`, `filepath`, `cooldown`, `price`, `owner_id`) VALUES ('snd_none', 'None', '', 0.0, 0, '\'STORE\'');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_trails`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_trails` (`item_id`, `name`, `vtf`, `vmt`, `price`, `owner_id`) VALUES ('trl_none', 'None', '', '', 0, '\'STORE\'');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_tags`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_tags` (`item_id`, `name`, `color_trie`, `price`, `owner_id`, `display`) VALUES ('tag_none', 'None', 'default', 0, 'STORE', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`str_upgrades`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`str_upgrades` (`item_id`, `name`, `description`, `price`, `owner_id`) VALUES ('ugd_none', 'None', 'None', 0, 'STORE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_classes`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (1, 'Scout');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (2, 'Soldier');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (3, 'Pyro');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (4, 'Demoman');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (5, 'Heavy');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (6, 'Engineer');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (7, 'Medic');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (8, 'Sniper');
INSERT INTO `quasar`.`tf_classes` (`id`, `name`) VALUES (9, 'Spy');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_particles`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_particles` (`id`, `name`, `type`, `system_name`) VALUES (0, 'None', 'None', 'none');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_paintkits`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (-1, 'UNDEFINED', 0, 0);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (1, 'A Color Similar to Slate', 3100495, 3100495);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (2, 'A Deep Commitment to Purple', 8208497, 8208497);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (3, 'A Distinctive Lack of Hue', 1315860, 1315860);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (4, 'A Mann\'s Mint', 12377523, 12377523);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (5, 'After Eight', 2960676, 2960676);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (6, 'Aged Moustache Grey', 8289918, 8289918);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (7, 'An Extraordinary Abundance of Tinge', 15132390, 15132390);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (8, 'Australium Gold', 15185211, 15185211);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (9, 'Color No. 216-190.216', 14204632, 14204632);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (10, 'Dark Salmon Injustice', 15308410, 15308410);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (11, 'Drably Olive', 8421376, 8421376);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (12, 'Indubitably Green', 7511618, 7511618);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (13, 'Mann Co. Orange', 13595446, 13595446);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (14, 'Muskelmannbraun', 10843461, 10843461);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (15, 'Noble Hatter\'s Violet', 5322826, 5322826);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (16, 'Peculiarly Drag Tincture', 12955537, 12955537);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (17, 'Pink as Hell', 16738740, 16738740);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (18, 'Radigan Conagher Brown', 6901050, 6901050);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (19, 'The Bitter Taste of Defeat and Lime', 3329330, 3329330);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (20, 'The Color of a Gentlemann\'s Business Pants', 15787660, 15787660);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (21, 'Ye Olde Rustic Color', 8154199, 8154199);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (22, 'Zepheniah\'s Greed', 	4345659, 	4345659);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (23, 'An Air of Debonair', 6637376, 2636109);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (24, 'Balaclavas Are Forever', 3874595, 1581885);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (25, 'Cream Spirit', 12807213, 12091445);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (26, 'Operator\'s Overalls', 4732984, 3686984);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (27, 'Team Spirit', 12073019, 5801378);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (28, 'The Value of Teamwork', 8400928, 2452877);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (29, 'Waterlogged Lab Coat', 11049612, 8626083);
INSERT INTO `quasar`.`tf_paintkits` (`id`, `name`, `red_color`, `blu_color`) VALUES (0, 'None', 16777215, 16777215);

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_items`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_items` (`id`, `name`, `classname`, `min_level`, `max_level`, `slot`) VALUES (-1, 'Default', 'no_entity', 0, 0, '0');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_qualities`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_qualities` (`id`, `name`) VALUES (0, 'None');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quasar`.`tf_warpaints`
-- -----------------------------------------------------
START TRANSACTION;
USE `quasar`;
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (102, 'Wrapped Reviver Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (104, 'Carpet Bomber Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (105, 'Masked Mender Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (106, 'Woodland Warrior Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (109, 'Forest Fire Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (113, 'Woodsy Widowmaker Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (114, 'Night Owl Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (11, 'Night Terror');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (120, 'Iron Wood Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (122, 'Plaid Potshotter Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (139, 'Civil Servant Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (13, 'Woodsy Widowmaker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (143, 'Smalltown Bringdown Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (144, 'Civic Duty Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (145, 'Liquid Asset');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (148, 'Pink Elephant');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (14, 'Night Owl');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (151, 'Dead Reckoner Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (15, 'Tartan Torpedo');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (160, 'Autumn Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (161, 'Nutcracker Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (16, 'Rustic Ruiner');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (17, 'Barn Burner');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (18, 'Homemade Heater');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (19, 'Lumber from Down Under');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (10, 'King of the Jungle');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (112, 'Backwoods Boomstick Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (12, 'Backwoods Boomstick');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (130, 'Bovine Blazemaker Mk.II');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (1, 'Sand Cannon');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (200, 'Bloom Buffed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (201, 'Quack Canvassed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (202, 'Bank Rolled');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (203, 'Merc Stained');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (204, 'Kill Covered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (205, 'Fire Glazed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (206, 'Pizza Polished');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (207, 'Bonk Varnished');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (208, 'Star Crossed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (209, 'Clover Camo\'d');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (20, 'Iron Wood');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (210, 'Freedom Wrapped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (211, 'Cardboard Boxed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (212, 'Dream Piped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (213, 'Miami Element');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (214, 'Neo Tokyo');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (215, 'Geometrical Teams');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (217, 'Bomber Soul');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (218, 'Uranium');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (21, 'Country Crusher');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (220, 'Cabin Fevered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (221, 'Polar Surprise');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (223, 'Hana');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (224, 'Dovetailed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (225, 'Cosmic Calamity');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (226, 'Hazard Warning');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (228, 'Mosaic');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (22, 'Plaid Potshotter');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (230, 'Jazzy');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (232, 'Alien Tech');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (234, 'Damascus and Mahogany');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (235, 'Skull Study');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (236, 'Haunted Ghosts');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (237, 'Spectral Shimmered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (238, 'Spirit of Halloween');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (239, 'Horror Holiday');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (23, 'Shot in the Dark');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (240, 'Totally Boned');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (241, 'Electroshocked');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (242, 'Ghost Town');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (243, 'Tumor Toasted');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (244, 'Calavera Canvas');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (245, 'Snow Covered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (246, 'Frost Ornamented');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (247, 'Smissmas Village');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (248, 'Igloo');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (249, 'Seriously Snowed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (24, 'Blasted Bombardier');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (250, 'Smissmas Camo');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (251, 'Sleighin\' Style');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (252, 'Alpine');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (253, 'Gift Wrapped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (254, 'Winterland Wrapped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (255, 'Helldriver');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (256, 'Organ-ically Hellraised');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (257, 'Spectrum Splattered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (258, 'Candy Coated');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (259, 'Pumpkin Pied');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (25, 'Reclaimed Reanimator');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (260, 'Sweet Toothed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (261, 'Crawlspace Critters');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (262, 'Portal Plastered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (263, 'Death Deluxe');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (264, 'Raving Dead');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (265, 'Eyestalker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (266, 'Spider\'s Cluster');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (267, 'Gourdy Green');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (268, 'Mummified Mimic');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (269, 'Spider Season');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (26, 'Antique Annihilator');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (270, 'Gingerbread Winner');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (271, 'Saccharine Striped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (272, 'Elfin Enamel');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (273, 'Peppermint Swirl');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (275, 'Snow Globalization');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (276, 'Gifting Mann\'s Wrapping Paper');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (277, 'Snowflake Swirled');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (278, 'Smissmas Spycrabs');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (279, 'Frozen Aurora');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (27, 'Old Country');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (280, 'Starlight Serenity');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (281, 'Frosty Delivery');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (282, 'Glacial Glazed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (283, 'Cookie Fortress');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (284, 'Sarsaparilla Sprayed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (285, 'Swashbuckled');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (286, 'Skull Cracked');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (287, 'Misfortunate');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (289, 'Neon-ween');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (28, 'American Pastoral');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (290, 'Simple Spirits');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (291, 'Broken Bones');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (292, 'Potent Poison');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (293, 'Searing Souls');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (294, 'Party Phantoms');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (295, 'Polter-Guised');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (296, 'Kiln and Conquer');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (297, 'Necromanced');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (29, 'Backcountry Blaster');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (2, 'Wrapped Reviver');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (300, 'Yeti Coated');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (301, 'Park Pigmented');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (302, 'Mannana Peeled');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (303, 'Macaw Masked');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (304, 'Sax Waxed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (305, 'Anodized Aloha');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (306, 'Bamboo Brushed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (307, 'Tiger Buffed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (308, 'Croc Dusted');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (309, 'Piña Polished');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (30, 'Bovine Blazemaker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (310, 'Leopard Printed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (31, 'War Room');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (32, 'Treadplate Tormenter');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (33, 'Bogtrotter');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (34, 'Earth, Sky and Fire');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (36, 'Spruce Deuce');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (37, 'Team Sprayer');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (38, 'Rooftop Wrangler');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (390, 'Dragon Slayer');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (391, 'Smissmas Sweater');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (39, 'Civil Servant');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (3, 'Psychedelic Slugger');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (400, 'Ghoul Blaster');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (401, 'Cream Corned');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (402, 'Sunriser');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (403, 'Sacred Slayer');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (404, 'Metalized Soul');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (405, 'Bonzo Gnawed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (406, 'Health and Hell');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (407, 'Health and Hell (Green)');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (408, 'Hypergon');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (409, 'Pumpkin Plastered');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (40, 'Citizen Pain');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (410, 'Chilly Autumn');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (411, 'Steel Brushed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (412, 'Secretly Serviced');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (413, 'Sky Stallion');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (414, 'Bomb Carrier');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (415, 'Business Class');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (416, 'Deadly Dragon');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (417, 'Team Serviced');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (418, 'Warborn');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (419, 'Pacific Peacemaker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (41, 'Local Hero');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (420, 'Mechanized Monster');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (421, 'Stardust');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (422, 'Team Detail');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (423, 'Gobi Glazed');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (424, 'Sleek Greek');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (35, 'Hickory Hole-Puncher');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (425, 'Graphite Gripped');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (426, 'Stealth Specialist');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (427, 'Piranha Mania');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (428, 'Team Charged');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (429, 'Brawler\'s Iron');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (42, 'Mayor');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (430, 'Necropolish');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (431, 'Blackout');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (432, 'Broken Record');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (43, 'Smalltown Bringdown');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (44, 'Civic Duty');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (45, 'Liquid Asset');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (46, 'Black Dahlia');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (47, 'Lightning Rod');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (48, 'Pink Elephant');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (49, 'Flash Fryer');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (4, 'Carpet Bomber');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (50, 'Spark of Life');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (51, 'Dead Reckoner');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (52, 'Shell Shocker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (53, 'Current Event');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (54, 'Turbine Torcher');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (55, 'Brick House');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (56, 'Sandstone Special');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (57, 'Aqua Marine');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (58, 'Low Profile');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (59, 'Thunderbolt');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (5, 'Masked Mender');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (60, 'Autumn');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (61, 'Nutcracker');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (62, 'Pumpkin Patch');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (63, 'Macabre Web');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (64, 'Boneyard');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (65, 'Wildwood');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (66, 'Balloonicorn');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (67, 'Rainbow');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (68, 'Sweet Dreams');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (69, 'Blew Mew');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (6, 'Woodland Warrior');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (70, 'Brain Candy');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (71, 'Stabbed to Hell');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (72, 'Flower Power');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (73, 'Mister Cuddles');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (74, 'Shot to Hell');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (75, 'Torqued to Hell');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (76, 'Coffin Nail');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (77, 'Top Shelf');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (78, 'Dressed to Kill');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (79, 'High Roller\'s');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (7, 'Purple Range');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (80, 'Warhawk');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (81, 'Blitzkrieg');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (82, 'Airwolf');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (83, 'Corsair');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (84, 'Butcher Bird');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (85, 'Killer Bee');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (86, 'Red Bear');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (8, 'Sudden Flurry');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (9, 'Forest Fire');
INSERT INTO `quasar`.`tf_warpaints` (`id`, `name`) VALUES (0, 'None');

COMMIT;

