/*
MAKE SURE YOU RUN setup_schema_plus_store.sql FIRST!

REPLACE srv_ WITH srv_<subdomain>_ !!!!
[srv1].example.com THE BOXED IN AREA IS THE SUBDOMAIN!
ALSO CHANGE THE VIEW NAMES AT THE BOTTOM FROM [SERVER Player Info]
TO [subdomain Player Info]!! SAME THING WITH THE STAR RATING VIEW!
*/

-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 19:42:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quasar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quasar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quasar` DEFAULT CHARACTER SET utf8 ;
USE `quasar` ;

-- -----------------------------------------------------
-- Table `quasar`.`srv_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_players` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `steam2_id` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `steam3_id` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `steam64_id` VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
  `points` DECIMAL NULL DEFAULT 0.0,
  `can_vote` INT NOT NULL DEFAULT 1,
  `name` VARCHAR(128) NOT NULL DEFAULT 'NONE',
  `num_loadouts` INT NOT NULL DEFAULT 1 COMMENT '`',
  `last_login` INT NOT NULL DEFAULT -1,
  `playtime` INT NOT NULL DEFAULT 0,
  `equipped_loadout` INT NOT NULL DEFAULT 1,
  `first_login` INT NOT NULL DEFAULT -1,
  `time_afk` INT UNSIGNED NOT NULL DEFAULT 0,
  `kills` INT NOT NULL DEFAULT 0,
  `afk_kills` INT NOT NULL DEFAULT 0,
  `afk_points` DECIMAL NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`, `steam64_id`, `steam2_id`, `steam3_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `steam64_id_UNIQUE` (`steam64_id` ASC) VISIBLE,
  UNIQUE INDEX `steam2_id_UNIQUE` (`steam2_id` ASC) VISIBLE,
  UNIQUE INDEX `steam3_id_UNIQUE` (`steam3_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_maps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_maps` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_maps` (
  `id` INT NOT NULL,
  `category` VARCHAR(64) NOT NULL DEFAULT 'NONE',
  `workshop_id` VARCHAR(128) NULL DEFAULT NULL,
  `author` VARCHAR(128) NULL DEFAULT 'UNKNOWN',
  `map` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`, `map`),
  UNIQUE INDEX `map_UNIQUE` (`map` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_playersmaps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_playersmaps` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_playersmaps` (
  `steam_id` VARCHAR(64) NOT NULL,
  `map` VARCHAR(128) NOT NULL,
  `rating` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`steam_id`, `map`),
  INDEX `FK_playersmaps_maps_idx` (`map` ASC) INVISIBLE,
  UNIQUE INDEX `steam_id_UNIQUE` (`steam_id` ASC) VISIBLE,
  UNIQUE INDEX `map_UNIQUE` (`map` ASC) VISIBLE,
  CONSTRAINT `FK_playersmaps_players`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_playersmaps_maps`
    FOREIGN KEY (`map`)
    REFERENCES `quasar`.`srv_maps` (`map`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_votelogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_votelogs` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_votelogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voter_name` VARCHAR(128) NOT NULL DEFAULT 'NONE',
  `voter_steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `votee_name` VARCHAR(128) NOT NULL DEFAULT 'NONE',
  `votee_steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `vote_type` INT NOT NULL DEFAULT 0,
  `date` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `voter_steam_id`),
  INDEX `FK_votelogs_players_idx` (`voter_steam_id` ASC) VISIBLE,
  INDEX `FK_votelogs_players2_idx` (`votee_steam_id` ASC) VISIBLE,
  CONSTRAINT `FK_votelogs_players`
    FOREIGN KEY (`voter_steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_votelogs_players2`
    FOREIGN KEY (`votee_steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_chatlogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_chatlogs` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_chatlogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT 'NONE',
  `steam_id` VARCHAR(64) NOT NULL,
  `message` VARCHAR(256) NULL DEFAULT 'NONE',
  `date` INT NOT NULL,
  PRIMARY KEY (`id`, `steam_id`),
  INDEX `FK_chatlogs_players_idx` (`steam_id` ASC) VISIBLE,
  CONSTRAINT `FK_chatlogs_players`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_mapsfeedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`srv_mapsfeedback` ;

CREATE TABLE IF NOT EXISTS `quasar`.`srv_mapsfeedback` (
  `steam_id` VARCHAR(64) NOT NULL,
  `map` VARCHAR(128) NOT NULL,
  `pos_x` DECIMAL NULL DEFAULT NULL,
  `pos_y` DECIMAL NULL DEFAULT NULL,
  `pos_z` DECIMAL NULL DEFAULT NULL,
  `ang_x` DECIMAL NULL DEFAULT NULL,
  `ang_y` DECIMAL NULL DEFAULT NULL,
  `ang_z` DECIMAL NULL DEFAULT NULL,
  `feedback` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`steam_id`, `feedback`, `map`),
  INDEX `FK_mapsfeedback_maps_idx` (`map` ASC) VISIBLE,
  CONSTRAINT `FK_mapsfeedback_maps`
    FOREIGN KEY (`map`)
    REFERENCES `quasar`.`srv_maps` (`map`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_mapsfeedback_players`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quasar`.`srv_playersignore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`qsr_playersignore` ;

CREATE TABLE IF NOT EXISTS `quasar`.`qsr_playersignore` (
  `steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `target_steam_id` VARCHAR(64) NOT NULL DEFAULT 0,
  `ignore_flags` INT NULL DEFAULT 0,
  PRIMARY KEY (`steam_id`, `target_steam_id`),
  CONSTRAINT `steam_id`
    FOREIGN KEY (`steam_id`)
    REFERENCES `quasar`.`srv_players` (`steam64_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `quasar` ;

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Sounds]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Sounds]` (`steam_id` INT, `item_id` INT, `name` INT, `filepath` INT, `cooldown` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Upgrades]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Upgrades]` (`steam_id` INT, `item_id` INT, `name` INT, `description` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Tags]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Tags]` (`steam_id` INT, `item_id` INT, `name` INT, `display` INT, `color_trie` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Trails]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Trails]` (`steam_id` INT, `item_id` INT, `name` INT, `vtf` INT, `vmt` INT, `price` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[Player Inventory]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[Player Inventory]` (`steam_id` INT, `item_id` INT, `upgrade_name` INT, `trail_name` INT, `sound_name` INT, `tag_name` INT, `upgrade_price` INT, `trail_price` INT, `sound_price` INT, `tag_price` INT, `upgrade_description` INT, `trail_vtf` INT, `trail_vmt` INT, `sound_filepath` INT, `sound_cooldown` INT, `tag_color` INT, `tag_display` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[SERVER Map Ratings]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[SERVER Map Ratings]` (`map` INT, `total_votes` INT, `rating` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quasar`.`[SERVER Player Info]`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quasar`.`[SERVER Player Info]` (`name` INT, `steam2_id` INT, `steam3_id` INT, `steam64_id` INT, `points` INT, `credits` INT, `num_loadouts` INT, `equipped_loadout` INT, `first_login` INT, `last_login` INT, `playtime` INT, `time_afk` INT);

-- -----------------------------------------------------
-- View `quasar`.`[Player Sounds]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Sounds]`;
DROP VIEW IF EXISTS `quasar`.`[Player Sounds]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Sounds]` AS
SELECT steam_id, pi.item_id, name, filepath, cooldown, price
FROM str_playersitems pi
	JOIN str_sounds snd
	ON pi.item_id = snd.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Upgrades]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Upgrades]`;
DROP VIEW IF EXISTS `quasar`.`[Player Upgrades]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Upgrades]` AS
SELECT steam_id, pi.item_id, name, description, price
FROM str_playersitems pi
	JOIN str_upgrades ugd
	ON pi.item_id = ugd.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Tags]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Tags]`;
DROP VIEW IF EXISTS `quasar`.`[Player Tags]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Tags]` AS
SELECT steam_id, pi.item_id, name, display, color_trie, price
FROM str_playersitems pi
	JOIN str_tags tag
	ON pi.item_id = tag.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Trails]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Trails]`;
DROP VIEW IF EXISTS `quasar`.`[Player Trails]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Trails]` AS
SELECT steam_id, pi.item_id, name, vtf, vmt, price
FROM str_playersitems pi
	JOIN str_trails trl
	ON pi.item_id = trl.item_id;

-- -----------------------------------------------------
-- View `quasar`.`[Player Inventory]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[Player Inventory]`;
DROP VIEW IF EXISTS `quasar`.`[Player Inventory]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[Player Inventory]` AS
SELECT  steam_id, pi.item_id,
		upg.name upgrade_name, trl.name trail_name, snd.name sound_name, tag.name tag_name,
		upg.price upgrade_price, trl.price trail_price, snd.price sound_price, tag.price tag_price,
		upg.description upgrade_description,
		trl.vtf trail_vtf, trl.vmt trail_vmt,
		snd.filepath sound_filepath, snd.cooldown sound_cooldown,
		tag.color_trie tag_color, tag.display tag_display
FROM str_playersitems pi
	LEFT JOIN str_upgrades upg
		ON pi.item_id = upg.item_id
	LEFT JOIN str_trails trl
		ON pi.item_id = trl.item_id
	LEFT JOIN str_sounds snd
		ON pi.item_id = snd.item_id
	LEFT JOIN str_tags tag
		ON pi.item_id = tag.item_id
GROUP BY pi.item_id, steam_id,
		upg.name, trl.name, snd.name, tag.name,
		upg.price, trl.price, snd.price, tag.price,
		upg.description,
		trl.vtf, trl.vmt,
		snd.filepath, snd.cooldown,
		tag.color_trie, tag.display;

-- -----------------------------------------------------
-- View `quasar`.`[SERVER Map Ratings]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[SERVER Map Ratings]`;
DROP VIEW IF EXISTS `quasar`.`[SERVER Map Ratings]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[SERVER Map Ratings]` AS
SELECT vt.map, total_votes, CAST(total_rating/SUM(total_votes) as decimal) rating
FROM (
	SELECT 	m.map,
			COUNT(DISTINCT steam_id) total_votes,
            SUM(pm.rating) total_rating
    FROM srv_maps m
		JOIN srv_playersmaps pm
			ON m.map = pm.map
	GROUP BY map
) AS vt
	JOIN srv_playersmaps pm
		ON vt.map = pm.map
GROUP BY map, total_votes
ORDER BY rating DESC;

-- -----------------------------------------------------
-- View `quasar`.`[SERVER Player Info]`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quasar`.`[SERVER Player Info]`;
DROP VIEW IF EXISTS `quasar`.`[SERVER Player Info]` ;
USE `quasar`;
CREATE  OR REPLACE VIEW `[SERVER Player Info]` AS
SELECT 	name, steam2_id, steam3_id, steam64_id,
		points, credits, num_loadouts, equipped_loadout,
        first_login, last_login, playtime, time_afk
FROM srv_players p
	JOIN str_playersbank b
		ON p.steam64_id = b.steam_id;
USE `quasar`;

DELIMITER $$

USE `quasar`$$
DROP TRIGGER IF EXISTS `quasar`.`srv_players_AFTER_INSERT` $$
USE `quasar`$$
CREATE DEFINER = CURRENT_USER TRIGGER `quasar`.`srv_players_AFTER_INSERT` AFTER INSERT ON `srv_players` FOR EACH ROW
BEGIN
    INSERT INTO str_playersgroups(steam_id, group_id) VALUES (NEW.steam64_id, 1) ON DUPLICATE KEY UPDATE steam_id = NEW.steam64_id;
	INSERT INTO str_playersbank (steam_id) VALUES (NEW.steam64_id) ON DUPLICATE KEY UPDATE steam_id = NEW.steam64_id;
END;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
